version: "3"
services:
  app:
    container_name: sample-vlang-api
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    networks:
      - fullstack

volumes:
  api:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
